### ISSUE TITLE
Insertion of non-serializable object leaves db in unusable state

### ISSUE THREAD

**Issue by dotsdl** [msiemens/tinydb#85] opened 2015-12-29 19:55 UTC
Attempting to insert a non-serializable python object results in an unusable tinydb. For example, doing:

```python
from tinydb import TinyDB

db = TinyDB('tinydb.json')
db.insert({'bark'})
```
results in an exception, which is good, but it also corrupts the db, which now looks like:

```
{"_default": {"1": 
```

This happens if the db also has other records.

**Comment by msiemens** [comment] 2015-12-29 20:09
Somehow I can't reproduce this with the latest development version. Which version of TinyDB do you use? Are you using the latest master from GitHub? Could you post the full stack trace you get?

**Comment by dotsdl** [comment] 2015-12-29 20:13
I'm using version 3.0.0. I'm not using the master branch from GitHub. Full stack trace below:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-879c6354d64c> in <module>()
----> 1 db.insert({'bark'})

/home/alter/.virtualenvs/datreant/lib/python2.7/site-packages/tinydb/database.pyc in insert(self, element)
    287         data = self._read()
    288         data[eid] = element
--> 289         self._write(data)
    290 
    291         return eid

/home/alter/.virtualenvs/datreant/lib/python2.7/site-packages/tinydb/database.pyc in _write(self, values)
    257 
    258         self._query_cache.clear()
--> 259         self._storage.write(values)
    260 
    261     def __len__(self):

/home/alter/.virtualenvs/datreant/lib/python2.7/site-packages/tinydb/database.pyc in write(self, values)
     43         data = self._storage.read() or {}
     44         data[self._table_name] = values
---> 45         self._storage.write(data)
     46 
     47 

/home/alter/.virtualenvs/datreant/lib/python2.7/site-packages/tinydb/storages.pyc in write(self, data)
    103     def write(self, data):
    104         self._handle.seek(0)
--> 105         json.dump(data, self._handle, **self.kwargs)
    106         self._handle.flush()
    107         self._handle.truncate()

/usr/lib64/python2.7/json/__init__.pyc in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, encoding, default, sort_keys, **kw)
    187     # could accelerate with writelines in some versions of Python, at
    188     # a debuggability cost
--> 189     for chunk in iterable:
    190         fp.write(chunk)
    191 

/usr/lib64/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    432                 yield chunk
    433         elif isinstance(o, dict):
--> 434             for chunk in _iterencode_dict(o, _current_indent_level):
    435                 yield chunk
    436         else:

/usr/lib64/python2.7/json/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    406                 else:
    407                     chunks = _iterencode(value, _current_indent_level)
--> 408                 for chunk in chunks:
    409                     yield chunk
    410         if newline_indent is not None:

/usr/lib64/python2.7/json/encoder.pyc in _iterencode_dict(dct, _current_indent_level)
    406                 else:
    407                     chunks = _iterencode(value, _current_indent_level)
--> 408                 for chunk in chunks:
    409                     yield chunk
    410         if newline_indent is not None:

/usr/lib64/python2.7/json/encoder.pyc in _iterencode(o, _current_indent_level)
    440                     raise ValueError("Circular reference detected")
    441                 markers[markerid] = o
--> 442             o = _default(o)
    443             for chunk in _iterencode(o, _current_indent_level):
    444                 yield chunk

/usr/lib64/python2.7/json/encoder.pyc in default(self, o)
    182 
    183         """
--> 184         raise TypeError(repr(o) + " is not JSON serializable")
    185 
    186     def encode(self, o):

TypeError: set(['bark']) is not JSON serializable
```

**Comment by msiemens** [comment] 2015-12-29 20:16
Okay, there was an issue about inserting objects that aren't dicts (#74) which was fixed by typechecking and throwing a `ValueError` (9eaf5626c2227ccf79e40441914a3ad3152b48dc). This fix hasn't been released yet and will most likely solve this issue too.

**Comment by dotsdl** [comment] 2015-12-29 20:17
Ah...sorry about that then. Glad it's taken care of!

**Comment by msiemens** [comment] 2015-12-29 20:18
No problem!

**Closed by msiemens** 2015-12-29 20:18 UTC
